/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tiki.seller.cli

import kotlinx.coroutines.runBlocking
import net.bramp.ffmpeg.FFmpeg
import picocli.CommandLine
import kotlin.system.exitProcess


@CommandLine.Command(
  subcommands = [
    CreateLiveStream::class,
    CommandLine.HelpCommand::class
  ]
)
object TikiLive

fun main(args: Array<String>): Unit = runBlocking {
  setUpEnv(args)
  exitProcess(CommandLine(TikiLive).execute(*(args.filter { it != "-prod" }.toTypedArray())))
}


fun setUpEnv(args: Array<String>) {
  if (args.contains("-prod")) {
    defaultPassword = "321"
  }
}
