package tiki.seller.cli

const val defaultStreamUrl = "https://tiki-mobile.s3-ap-southeast-1.amazonaws.com/tikilive/stream_sync.mp4"
const val defaultUserName = "live2@gmail.com"
var defaultPassword = "123456"
const val defaultThumbUrl = "https://uat.tikicdn.com/ts/tikilive/ef/d5/06/6c27aa55e88d6e353d37238fdc7a7470.jpg"
const val defaultStreamHashTag = "#camera"
const val defaultStreamTitle = "Generated by seller center cli"
const val defaultStreamProductIds = "1,2,3"